version: "3"
services:
  mysqldb:
    image: mysql:8
    networks:
      - mysql-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employeedb
    
  employee-jdbc:
    image: itzmekk/employee-jdbc
    ports:
      - "8092:8080"
    networks:
      - mysql-network
    depends_on:
      - mysqldb

networks:
  mysql-network:
