version: "3"
services:
  employee-jdbc:
    image: itzmekk/employee-jdbc
    ports:
      - "8095:8080"
    networks:
      - employee-mysql-network
    depends_on:
      - mysqldb-employee-jdbc
 
  mysqldb-employee-jdbc:
    image: mysql:8
    networks:
      - employee-mysql-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employeedb  

networks:
  employee-mysql-network:
