version: "3"
services:
  mysqldb-employee-jdbc:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employeedb
    
  employee-jdbc:
    depends_on:
      - mysqldb-employee-jdbc:
    image: itzmekk/employee-jdbc
    ports:
      - "8092:8080"


    


